# Generated by Django 6.1.1 on 2026-09-21 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='نام پایه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پایه',
                'verbose_name_plural': 'پایه ها',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='MajorCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='نام رشته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'رشته ',
                'verbose_name_plural': 'رشته ها',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='ProvinceCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان ها',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='CityCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='categories.provincecategories', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر ها',
                'ordering': ['-sort_number'],
            },
        ),
    ]
