# Generated by Django 6.1.1 on 2026-09-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='نام درس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'درس ',
                'verbose_name_plural': 'دروس',
                'ordering': ['-sort_number'],
            },
        ),
    ]
