# Generated by Django 6.1.1 on 2026-09-21 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_lessoncategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycategories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citycategories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='gradecategories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradecategories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='lessoncategories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessoncategories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='majorcategories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majorcategories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='provincecategories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provincecategories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='citycategories',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AlterField(
            model_name='gradecategories',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AlterField(
            model_name='lessoncategories',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AlterField(
            model_name='majorcategories',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
