# Generated by Django 6.1.1 on 2026-09-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_citycategories_created_at_citycategories_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی های مقالات',
                'ordering': ['-sort_number', '-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='citycategories',
            options={'ordering': ['-sort_number', '-pk'], 'verbose_name': 'شهر', 'verbose_name_plural': 'شهر ها'},
        ),
        migrations.AlterModelOptions(
            name='gradecategories',
            options={'ordering': ['-sort_number', '-pk'], 'verbose_name': 'پایه', 'verbose_name_plural': 'پایه ها'},
        ),
        migrations.AlterModelOptions(
            name='lessoncategories',
            options={'ordering': ['-sort_number', '-pk'], 'verbose_name': 'درس ', 'verbose_name_plural': 'دروس'},
        ),
        migrations.AlterModelOptions(
            name='majorcategories',
            options={'ordering': ['-sort_number', '-pk'], 'verbose_name': 'رشته ', 'verbose_name_plural': 'رشته ها'},
        ),
        migrations.AlterModelOptions(
            name='provincecategories',
            options={'ordering': ['-sort_number', '-pk'], 'verbose_name': 'استان', 'verbose_name_plural': 'استان ها'},
        ),
    ]
