# Generated by Django 6.1.1 on 2026-09-23 21:14

import django.db.models.manager
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_blogcategories_alter_citycategories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogcategories',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='citycategories',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='gradecategories',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lessoncategories',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='majorcategories',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='provincecategories',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='blogcategories',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='blogcategories',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='citycategories',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='citycategories',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='gradecategories',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='gradecategories',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='lessoncategories',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='lessoncategories',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='majorcategories',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='majorcategories',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='provincecategories',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='provincecategories',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
    ]
