# Generated by Django 6.1.1 on 2026-09-21 20:35

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='classes.class', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ClassFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='فایل')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='classes.class', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'فایل کلاس',
                'verbose_name_plural': 'فایل های کلاس',
                'ordering': ['-pk'],
            },
        ),
    ]
