# Generated by Django 6.1.1 on 2026-09-21 21:03

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_created_at_class_sort_number_class_updated_at'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classarticle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AddField(
            model_name='classarticle',
            name='sort_number',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب'),
        ),
        migrations.AddField(
            model_name='classarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='classfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classfile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AddField(
            model_name='classfile',
            name='sort_number',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب'),
        ),
        migrations.AddField(
            model_name='classfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.CreateModel(
            name='ClassPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='classes.class', verbose_name='تمرین')),
            ],
            options={
                'verbose_name': 'تمرین',
                'verbose_name_plural': 'تمرینات',
                'ordering': ['-pk'],
            },
        ),
    ]
