# Generated by Django 6.1.1 on 2026-09-23 21:14

import django.db.models.manager
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_classarticle_created_at_classarticle_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='classarticle',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='classfile',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='classpractice',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='classarticle',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='classarticle',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='classfile',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='classfile',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='classpractice',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='classpractice',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
    ]
