# Generated by Django 6.1.1 on 2026-09-24 17:39

import apps.common.models_fields
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_class_image_class_is_free_class_is_public_and_more'),
        ('content', '0004_alter_classarticle_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classarticle',
            name='klass',
        ),
        migrations.RemoveField(
            model_name='classfile',
            name='klass',
        ),
        migrations.RemoveField(
            model_name='classpractice',
            name='klass',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='classes.class', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسه ها',
                'ordering': ['-pk'],
            },
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='classarticle',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='content.section', verbose_name='مقاله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classfile',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='content.section', verbose_name='فایل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classpractice',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='content.section', verbose_name='تمرین'),
            preserve_default=False,
        ),
    ]
