# Generated by Django 6.1.1 on 2026-09-24 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_class_grade_alter_class_lesson_and_more'),
        ('content', '0005_remove_classarticle_klass_remove_classfile_klass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='classes.class', verbose_name='کلاس'),
        ),
    ]
