# Generated by Django 6.1.1 on 2026-09-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_section_klass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classarticle',
            options={'ordering': ['-sort_number', '-pk'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='classfile',
            options={'ordering': ['-sort_number', '-pk'], 'verbose_name': 'فایل کلاس', 'verbose_name_plural': 'فایل های کلاس'},
        ),
        migrations.AlterModelOptions(
            name='classpractice',
            options={'ordering': ['-sort_number', '-pk'], 'verbose_name': 'تمرین', 'verbose_name_plural': 'تمرینات'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-sort_number', '-pk'], 'verbose_name': 'جلسه', 'verbose_name_plural': 'جلسه ها'},
        ),
        migrations.AddField(
            model_name='section',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='انتشار'),
        ),
    ]
