# Generated by Django 6.1.1 on 2026-09-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_classarticle_options_alter_classfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classarticle',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classfile',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classpractice',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
