# Generated by Django 6.1.1 on 2026-09-21 18:28

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره والدین')),
                ('school', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام مدرسه')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='categories.citycategories', verbose_name='شهر')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='categories.gradecategories', verbose_name='پایه')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='categories.majorcategories', verbose_name='رشته تحصیلی')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='categories.provincecategories', verbose_name='استان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب')),
            ],
            options={
                'verbose_name': 'پروفایل دانش اموز',
                'verbose_name_plural': 'پروفایل های دانش اموزان',
                'ordering': ['-pk'],
            },
        ),
    ]
