# Generated by Django 6.1.1 on 2026-09-21 20:35

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_lessoncategories'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='categories.citycategories', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='categories.gradecategories', verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='categories.majorcategories', verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='شماره والدین'),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='categories.provincecategories', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='مدرسه'),
        ),
    ]
