# Generated by Django 6.1.1 on 2026-09-24 18:10

import apps.common.models_fields
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_city_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=apps.common.models_fields.BaseJalaliDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AddField(
            model_name='student',
            name='sort_number',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=apps.common.models_fields.BaseJalaliDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
    ]
