# Generated by Django 6.1.1 on 2026-10-05 20:16

import apps.common.file_storage_script_for_model
import apps.common.models_fields
import django.db.models.deletion
import django.db.models.manager
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات ')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.common.file_storage_script_for_model.UploadPath('tickets/'), verbose_name='پیوست')),
                ('priority', models.CharField(choices=[('پایین', 'پایین'), ('متوسط', 'متوسط'), ('بالا', 'بالا'), ('فوری', 'فوری')], max_length=255, verbose_name='اهمیت')),
                ('status', models.CharField(choices=[('کنسل شده', 'کنسل شده'), ('حل شده', 'حل شده'), ('در انتظار پاسخ ادمین', 'در انتظار پاسخ ادمین'), ('در انتظار پاسخ کاربر', 'در انتظار کاربر')], max_length=255, verbose_name='وضعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='درخواست دهنده')),
            ],
            options={
                'verbose_name': 'تیکت ',
                'verbose_name_plural': 'تیکت  ها',
                'ordering': ['-id'],
            },
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TicketChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('is_read_by_user', models.BooleanField(default=False, verbose_name='خوانده شده توسط کاربر')),
                ('admin_message', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='پیام')),
                ('user_message', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_admin', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='ticket.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام تیکت  ',
                'verbose_name_plural': 'پیام های تیکت',
                'ordering': ['id'],
            },
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
