# Generated by Django 6.1.1 on 2026-09-21 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_lessoncategories'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='grade',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='categories.citycategories', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='categories.majorcategories', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='categories.provincecategories', verbose_name='استان'),
        ),
    ]
