# Generated by Django 6.1.1 on 2026-09-21 21:40

import apps.questions.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_citycategories_created_at_citycategories_updated_at_and_more'),
        ('content', '0002_classarticle_created_at_classarticle_is_active_and_more'),
        ('exams', '0001_initial'),
        ('students', '0002_alter_student_city_alter_student_grade_and_more'),
        ('teachers', '0002_remove_teacher_grade_alter_teacher_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='متن سوال')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.questions.models.photo_path_upload_to, verbose_name='تصویر سوال')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.questions.models.photo_path_upload_to, verbose_name='فایل PDF سوال')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان سوال')),
                ('type_of_question', models.CharField(choices=[('تستی چند گزینه\u200cای', 'تستی چند گزینه\u200cای'), ('پاسخ کوتاه', 'پاسخ کوتاه'), ('پاسخ تشریحی', 'پاسخ تشریحی'), ('مبتنی بر تصویر', 'مبتنی بر تصویر'), ('سوال از فایل PDF', 'سوال از فایل PDF')], max_length=100, verbose_name='نوع سوال')),
                ('score', models.FloatField(default=1, verbose_name='حداکثر نمره سوال')),
                ('is_for_qbank', models.BooleanField(default=False, verbose_name='سوال جزو بانک سوال ؟')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='exams.exam', verbose_name='ازمون')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='categories.gradecategories', verbose_name='پایه')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='categories.lessoncategories', verbose_name='درس')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='categories.majorcategories', verbose_name='رشته')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='content.classpractice', verbose_name='تمرین')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['-sort_number', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('type_of_answer', models.CharField(choices=[('پاسخ تشریحی', 'پاسخ تشریحی'), ('پاسخ تصویری', 'پاسخ تصویری'), ('پاسخ PDF', 'پاسخ PDF')], max_length=50, verbose_name='نوع پاسخ صحیح')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='متن پاسخ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.questions.models.photo_path_upload_to, verbose_name='تصویر پاسخ')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.questions.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key', to='questions.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ صحیح (ادمین)',
                'verbose_name_plural': 'پاسخ\u200cهای صحیح (ادمین)',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('text', models.CharField(max_length=500, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='گزینه صحیح')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': ' گزینه سوال تست',
                'verbose_name_plural': 'گزینه\u200cها سوالات تستی',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('type_of_answer', models.CharField(choices=[('انتخاب گزینه', 'انتخاب گزینه'), ('پاسخ متنی', 'پاسخ متنی'), ('پاسخ تصویری', 'پاسخ تصویری'), ('پاسخ PDF', 'پاسخ PDF'), ('رد شده', 'رد شده'), ('جواب داده نشده', 'جواب داده نشده')], default='جواب داده نشده', max_length=50, verbose_name='نوع پاسخ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.questions.models.photo_path_upload_to, verbose_name='تصویر پاسخ')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.questions.models.photo_path_upload_to, verbose_name='فایل PDF پاسخ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='متن پاسخ')),
                ('sanatorium_message', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='نظر مصصح')),
                ('corrected', models.CharField(choices=[('تصحیح نشده', 'تصحیح نشده'), ('کاملا اشتباه', 'کاملا اشتباه'), ('نیاز به تلاش بیشتر', 'نیاز به تلاش بیشتر'), ('قابل قبول', 'قابل قبول'), ('نسبتا درست', 'نسبتا درست'), ('کاملا درست', 'کاملا درست')], default='تصحیح نشده', max_length=100, verbose_name='کیفیت جواب')),
                ('corrected_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصحیح')),
                ('score', models.FloatField(default=0, verbose_name='نمره داده شده')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_answers', to='teachers.teacher', verbose_name='تصحیح\u200cکننده')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='questions.question', verbose_name='سوال')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.questionoption', verbose_name='گزینه انتخاب\u200cشده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='students.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ دانش\u200cآموز',
                'verbose_name_plural': 'پاسخ\u200cهای دانش\u200cآموزان',
                'ordering': ['student'],
                'unique_together': {('student', 'question')},
            },
        ),
    ]
