# Generated by Django 6.1.1 on 2026-09-24 17:39

import apps.common.file_storage_script_for_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_question_image_alter_question_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.file_storage_script_for_model.UploadPath('questions'), verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.file_storage_script_for_model.UploadPath('questions'), verbose_name='فایل PDF سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.file_storage_script_for_model.UploadPath('questions/key/'), verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionanswerkey',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.file_storage_script_for_model.UploadPath('questions/key/'), verbose_name='فایل PDF پاسخ'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.file_storage_script_for_model.UploadPath('student-answers'), verbose_name='تصویر پاسخ'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.file_storage_script_for_model.UploadPath('student-answers'), verbose_name='فایل PDF پاسخ'),
        ),
    ]
