# Generated by Django 6.1.1 on 2026-09-24 13:42

import apps.common.file_storage_script_for_model
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='معرفی کوتاه'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=80, scale=None, size=None, upload_to=apps.common.file_storage_script_for_model.UploadPath('users-profile'), verbose_name='عکس'),
        ),
    ]
