# Generated by Django 6.1.1 on 2026-09-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_biography_user_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-sort_number', '-pk'), 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='user',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='انتشار'),
        ),
        migrations.AddField(
            model_name='user',
            name='sort_number',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب'),
        ),
    ]
