# Generated by Django 6.1.1 on 2026-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_user_publish_user_sort_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تلرام'),
        ),
    ]
