# Generated by Django 6.1.1 on 2026-09-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_class_created_at_class_sort_number_class_updated_at'),
        ('students', '0002_alter_student_city_alter_student_grade_and_more'),
        ('teachers', '0002_remove_teacher_grade_alter_teacher_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('content', models.TextField(verbose_name='متن')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='classes.class', verbose_name='کلاس')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='students.student', verbose_name='دانش اموز')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='teachers.teacher', verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'پیام کلاس',
                'verbose_name_plural': 'پیام های کلاسی',
                'ordering': ['pk'],
            },
        ),
    ]
