# Generated by Django 6.1.1 on 2026-09-23 21:14

import django.db.models.manager
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0002_site_delete_classmessage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='site',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='list_articles_above_tag',
            field=models.CharField(default=' مقالات آموزشی ', max_length=100, verbose_name='تگ لیست مقالات'),
        ),
        migrations.AddField(
            model_name='site',
            name='list_articles_description',
            field=models.CharField(default='اگاهی و دانایی بیشتر با مطالعه بیشتر', max_length=500, verbose_name='توضیحات لیست مقالات'),
        ),
        migrations.AddField(
            model_name='site',
            name='list_articles_title',
            field=models.CharField(default=' مقالات آموزشی امورشی فراسو', max_length=100, verbose_name='عنوان لیست مقالات'),
        ),
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(default='بنیاد اموزشی فراسو', max_length=100, verbose_name='نام سایت'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
    ]
