# Generated by Django 6.1.1 on 2026-09-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0003_alter_site_managers_site_list_articles_above_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-pk'], 'verbose_name': 'تنظیمات', 'verbose_name_plural': 'تنظیمات'},
        ),
    ]
