# Generated by Django 6.1.1 on 2026-09-24 13:34

import apps.common.models_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0004_alter_site_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='created_at',
            field=apps.common.models_fields.BaseJalaliDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated_at',
            field=apps.common.models_fields.BaseJalaliDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
    ]
