# Generated by Django 6.1.1 on 2026-09-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0005_alter_site_created_at_alter_site_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='list_course_above_tag',
            field=models.CharField(default=' دوره\u200cهای تخصصی ', max_length=100, verbose_name='تگ لیست دوره ها'),
        ),
        migrations.AddField(
            model_name='site',
            name='list_course_description',
            field=models.CharField(default='دوره\u200cهایی که آینده شما را می\u200cسازند', max_length=500, verbose_name='توضیحات لیست دوره ها'),
        ),
        migrations.AddField(
            model_name='site',
            name='list_course_title',
            field=models.CharField(default=' دورهای امورشی فراسو', max_length=100, verbose_name='عنوان لیست دوره ها'),
        ),
        migrations.AlterField(
            model_name='site',
            name='list_articles_title',
            field=models.CharField(default=' مقالات امورشی فراسو', max_length=100, verbose_name='عنوان لیست مقالات'),
        ),
    ]
