# Generated by Django 6.1.1 on 2026-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0006_site_list_course_above_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='count_of_courses_in_course_detail_page',
            field=models.IntegerField(default=6, verbose_name='تعداد نمایشی دوره ها در صفحه جزییات دوره'),
        ),
    ]
