# Generated by Django 6.1.1 on 2026-09-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0007_site_count_of_courses_in_course_detail_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='list_users_above_tag',
            field=models.CharField(default='اعضایی گرامی', max_length=100, verbose_name='تگ لیست کاربران'),
        ),
        migrations.AddField(
            model_name='site',
            name='list_users_description',
            field=models.CharField(default='افرادی که اینده را میسازند', max_length=500, verbose_name='توضیحات لیست کاربران'),
        ),
        migrations.AddField(
            model_name='site',
            name='list_users_title',
            field=models.CharField(default=' اعضای سایت امورشی فراسو', max_length=100, verbose_name='عنوان لیست کاربران'),
        ),
    ]
