# Generated by Django 6.1.1 on 2026-09-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0008_site_list_users_above_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='list_exam_above_tag',
            field=models.CharField(default='سنجش و یادگیری', max_length=100, verbose_name='تگ لیست ازمون ها'),
        ),
        migrations.AddField(
            model_name='site',
            name='list_exam_description',
            field=models.CharField(default='داشن خود را به چالش بکشید', max_length=500, verbose_name='توضیحات لیست ازمون ها'),
        ),
        migrations.AddField(
            model_name='site',
            name='list_exam_title',
            field=models.CharField(default=' ازمون های امورشی فراسو', max_length=100, verbose_name='عنوان لیست ازمون ها'),
        ),
    ]
