# Generated by Django 6.1.1 on 2026-09-25 10:04

import apps.common.models_fields
import django.db.models.manager
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0009_site_list_exam_above_tag_site_list_exam_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام')),
                ('read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره تماس ')),
                ('message', models.TextField(verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'ordering': ['pk'],
            },
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='active_contact',
            field=models.BooleanField(default=True, verbose_name='فعال صفحه تماس با ما'),
        ),
        migrations.AddField(
            model_name='site',
            name='active_counseling',
            field=models.BooleanField(default=True, verbose_name='فعال صفحه مشاوره رایگان'),
        ),
        migrations.AddField(
            model_name='site',
            name='contact_above_tag',
            field=models.CharField(default=' ارتباط با ما', max_length=100, verbose_name='تگ تماس با ما'),
        ),
        migrations.AddField(
            model_name='site',
            name='contact_description',
            field=models.CharField(default='ما در سریعترین زمان به پیام شما پاسخ خواهیم داد', max_length=500, verbose_name='توضیحات تماس با ما'),
        ),
        migrations.AddField(
            model_name='site',
            name='contact_title',
            field=models.CharField(default='پیام خود را ارسال کنید', max_length=100, verbose_name='عنوان تماس با ما'),
        ),
        migrations.AddField(
            model_name='site',
            name='email_contact',
            field=models.EmailField(default='maryus19915123@gmail.com', max_length=254, verbose_name='ایمیل صفحه تماس با ما'),
        ),
        migrations.AddField(
            model_name='site',
            name='email_counseling',
            field=models.EmailField(default='maryus19915123@gmail.com', max_length=254, verbose_name='ایمیل صفحه صفحه مشاوره رایگان'),
        ),
        migrations.AddField(
            model_name='site',
            name='free_counseling_above_tag',
            field=models.CharField(default=' ارتباط با ما', max_length=100, verbose_name='تگ مشاوره رایگان'),
        ),
        migrations.AddField(
            model_name='site',
            name='free_counseling_description',
            field=models.CharField(default='ما در سریعترین زمان به پیام شما پاسخ خواهیم داد', max_length=500, verbose_name='توضیحات مشاوره رایگان'),
        ),
        migrations.AddField(
            model_name='site',
            name='free_counseling_title',
            field=models.CharField(default='پیام خود را ارسال کنید', max_length=100, verbose_name='عنوان مشاوره رایگان'),
        ),
        migrations.AddField(
            model_name='site',
            name='phone_number_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(default='09373061991', max_length=128, region=None, verbose_name='شماره تماس صفحه تماس با ما'),
        ),
        migrations.AddField(
            model_name='site',
            name='phone_number_counseling',
            field=phonenumber_field.modelfields.PhoneNumberField(default='09373061991', max_length=128, region=None, verbose_name='شماره تماس صفحه صفحه مشاوره رایگان'),
        ),
        migrations.AlterField(
            model_name='site',
            name='count_of_courses_in_course_detail_page',
            field=models.IntegerField(default=6, verbose_name='تعداد نمایشی دوره ها در صفحه جزییات '),
        ),
    ]
