# Generated by Django 6.1.1 on 2026-09-25 11:02

import apps.common.models_fields
import django.db.models.manager
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0010_contact_site_active_contact_site_active_counseling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام')),
                ('read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره تماس ')),
                ('message', models.TextField(verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست های مشاوره',
                'ordering': ['-read', 'pk'],
            },
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-read', 'pk'], 'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
        migrations.AlterField(
            model_name='site',
            name='free_counseling_above_tag',
            field=models.CharField(default='آماده\u200cای که شروع کنیم؟', max_length=100, verbose_name='تگ مشاوره رایگان'),
        ),
        migrations.AlterField(
            model_name='site',
            name='free_counseling_description',
            field=models.CharField(default='برای مشاوره رایگان فرم رو پر کن. کمتر از ۲۴ ساعت تماس می\u200cگیریم.', max_length=500, verbose_name='توضیحات مشاوره رایگان'),
        ),
        migrations.AlterField(
            model_name='site',
            name='free_counseling_title',
            field=models.CharField(default=' مشاوره رایگان', max_length=100, verbose_name='عنوان مشاوره رایگان'),
        ),
    ]
