# Generated by Django 6.1.1 on 2026-09-25 11:41

import apps.common.models_fields
import django.db.models.manager
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0011_counseling_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('question', models.CharField(max_length=500, verbose_name='سوال')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['-sort_number', '-pk'],
            },
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='faq_above_tag',
            field=models.CharField(default='سوالی داری؟ ', max_length=100, verbose_name='تگ پرسش پاسخ'),
        ),
        migrations.AddField(
            model_name='site',
            name='faq_active',
            field=models.BooleanField(default=True, verbose_name='فعال صفحه پرسش پاسخ'),
        ),
        migrations.AddField(
            model_name='site',
            name='faq_description',
            field=models.CharField(default='پاسخ به سوالات متداول', max_length=500, verbose_name='توضیحات پرسش پاسخ'),
        ),
        migrations.AddField(
            model_name='site',
            name='faq_title',
            field=models.CharField(default=' سوالات متداول', max_length=100, verbose_name='عنوان پرسش پاسخ'),
        ),
    ]
