# Generated by Django 6.1.1 on 2026-09-25 12:37

import apps.common.file_storage_script_for_model
import apps.common.models_fields
import django.db.models.manager
import django_ckeditor_5.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0012_faq_site_faq_above_tag_site_faq_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMonomials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('text', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=False, quality=80, scale=None, size=None, upload_to=apps.common.file_storage_script_for_model.UploadPath('test-monomials'), verbose_name='عکس')),
                ('behave', models.CharField(max_length=255, verbose_name='سابقه')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-sort_number', '-pk'],
            },
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', apps.common.models_fields.BaseJalaliDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('svq', models.TextField(default='\n        <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">\n            <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>\n            <polyline points="22 4 12 14.01 9 11.01"></polyline>\n        </svg>\n    ', verbose_name='svg ایکون')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تایم لاین',
                'verbose_name_plural': 'تایم لاین ها',
                'ordering': ['-sort_number', 'pk'],
            },
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='about_above_tag',
            field=models.CharField(default='با ما اشنا شوید', max_length=100, verbose_name='تگ درباره ما'),
        ),
        migrations.AddField(
            model_name='site',
            name='about_active',
            field=models.BooleanField(default=True, verbose_name='فعال صفحه درباره ما'),
        ),
        migrations.AddField(
            model_name='site',
            name='about_title',
            field=models.CharField(default='درباره ما', max_length=100, verbose_name='عنوان درباره ما'),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='توضیحات'),
        ),
    ]
