# Generated by Django 6.1.1 on 2026-09-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0013_testmonomials_timeline_site_about_above_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='auth_title',
            field=models.CharField(default='خوش امدید', max_length=100, verbose_name='عنوان احراز هویت'),
        ),
        migrations.AddField(
            model_name='site',
            name='forgot_password_active',
            field=models.BooleanField(default=True, verbose_name='فعال کردن فراموشی رمز'),
        ),
        migrations.AddField(
            model_name='site',
            name='login_active',
            field=models.BooleanField(default=True, verbose_name='فعال کردن ورود'),
        ),
        migrations.AddField(
            model_name='site',
            name='logo_svg',
            field=models.CharField(default='\n        <svg width="45" height="45" viewBox="0 0 100 100" fill="none">\n            <defs><linearGradient id="smallGrad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#00f2fe"/><stop offset="100%" stop-color="#4facfe"/></linearGradient></defs>\n            <circle cx="50" cy="50" r="46" stroke="url(#smallGrad)" stroke-width="4" fill="none"/>\n            <circle cx="50" cy="50" r="14" fill="url(#smallGrad)"/>\n        </svg>\n    ', max_length=500, verbose_name='svg لوگو سایت'),
        ),
        migrations.AddField(
            model_name='site',
            name='register_active',
            field=models.BooleanField(default=True, verbose_name='فعال کردن ثبت نام'),
        ),
    ]
