# Generated by Django 6.1.1 on 2026-09-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0014_site_auth_title_site_forgot_password_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='footer_fast_link_1_name',
            field=models.URLField(default='خانه', verbose_name='نام لینک شماره ۱ سریع فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_fast_link_1_url',
            field=models.URLField(default='/', verbose_name='لینک شماره ۱ سریع فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_fast_link_2_name',
            field=models.URLField(default='دورها', verbose_name='نام لینک شماره ۲ سریع فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_fast_link_2_url',
            field=models.URLField(default='/courses/', verbose_name=' لینک شماره ۲ سریع فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_fast_link_3_name',
            field=models.URLField(default='مقالات', verbose_name='نام لینک شماره ۳ سریع فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_fast_link_3_url',
            field=models.URLField(default='/posts/', verbose_name=' لینک شماره ۳ سریع فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_fast_link_4_name',
            field=models.URLField(default='ازمون ها', verbose_name='نام لینک شماره ۴ سریع فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_fast_link_4_url',
            field=models.URLField(default='/exams/', verbose_name=' لینک شماره ۴ سریع فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_important_1_name',
            field=models.URLField(default='ورود یا ثبت نام', verbose_name='نام لینک مهم شماره ۱ فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_important_1_url',
            field=models.URLField(default='/users/auth/', verbose_name='لینک مهم شماره ۱ فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_important_2_name',
            field=models.URLField(default='درباره ما', verbose_name='نام لینک مهم شماره ۲ فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_important_2_url',
            field=models.URLField(default='/about/', verbose_name=' لینک مهم شماره ۲ فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_important_3_name',
            field=models.URLField(default='تماس با ما', verbose_name='نام لینک مهم شماره ۳ فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_important_3_url',
            field=models.URLField(default='/contact/', verbose_name=' لینک مهم شماره ۳ فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_important_4_name',
            field=models.URLField(default='درخواست مشاوره رایگان', verbose_name='نام لینک مهم شماره ۴ فوتر'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_important_4_url',
            field=models.URLField(default='/free-counseling/', verbose_name=' لینک مهم شماره ۴ فوتر'),
        ),
    ]
