# Generated by Django 6.1.1 on 2026-09-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0015_site_footer_fast_link_1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='copyright',
            field=models.CharField(default='© ۲۰۲۶ آکادمی فراسو برای اینده ای بهتر', max_length=150, verbose_name='کپی رایت'),
        ),
        migrations.AddField(
            model_name='site',
            name='developer_message',
            field=models.CharField(default='نوشته شده با ❤️ توسط maryus', max_length=50, verbose_name='پیام طراح'),
        ),
        migrations.AddField(
            model_name='site',
            name='link_url',
            field=models.URLField(default='https://github.com/maryus1991/CompleteOnlineSchoolSystem', verbose_name='لینک طراح'),
        ),
        migrations.AlterField(
            model_name='site',
            name='footer_fast_link_1_name',
            field=models.CharField(default='خانه', max_length=50, verbose_name='نام لینک شماره ۱ سریع فوتر'),
        ),
        migrations.AlterField(
            model_name='site',
            name='footer_fast_link_2_name',
            field=models.CharField(default='دورها', max_length=50, verbose_name='نام لینک شماره ۲ سریع فوتر'),
        ),
        migrations.AlterField(
            model_name='site',
            name='footer_fast_link_3_name',
            field=models.CharField(default='مقالات', max_length=50, verbose_name='نام لینک شماره ۳ سریع فوتر'),
        ),
        migrations.AlterField(
            model_name='site',
            name='footer_fast_link_4_name',
            field=models.CharField(default='ازمون ها', max_length=50, verbose_name='نام لینک شماره ۴ سریع فوتر'),
        ),
        migrations.AlterField(
            model_name='site',
            name='footer_important_1_name',
            field=models.CharField(default='ورود یا ثبت نام', max_length=50, verbose_name='نام لینک مهم شماره ۱ فوتر'),
        ),
        migrations.AlterField(
            model_name='site',
            name='footer_important_2_name',
            field=models.CharField(default='درباره ما', max_length=50, verbose_name='نام لینک مهم شماره ۲ فوتر'),
        ),
        migrations.AlterField(
            model_name='site',
            name='footer_important_3_name',
            field=models.CharField(default='تماس با ما', max_length=50, verbose_name='نام لینک مهم شماره ۳ فوتر'),
        ),
        migrations.AlterField(
            model_name='site',
            name='footer_important_4_name',
            field=models.CharField(default='درخواست مشاوره رایگان', max_length=50, verbose_name='نام لینک مهم شماره ۴ فوتر'),
        ),
    ]
