# Generated by Django 6.1.1 on 2026-09-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0016_site_copyright_site_developer_message_site_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='instagram_link',
            field=models.URLField(default='#', verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='site',
            name='other_link',
            field=models.URLField(default='#', verbose_name='لینک های دیگر'),
        ),
        migrations.AddField(
            model_name='site',
            name='short_description',
            field=models.CharField(default='بنیادی هستیم که برای تضمین اینده شما امده ایم', max_length=255, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='site',
            name='telegram_link',
            field=models.URLField(default='#', verbose_name='لینک تلرام'),
        ),
    ]
