# Generated by Django 6.1.1 on 2026-09-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0017_site_instagram_link_site_other_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='list_articles_active',
            field=models.BooleanField(default=True, verbose_name='فعال صفحه لیست مقالات'),
        ),
        migrations.AddField(
            model_name='site',
            name='list_course_active',
            field=models.BooleanField(default=True, verbose_name='فعال صفحه لیست دوره ها'),
        ),
        migrations.AddField(
            model_name='site',
            name='list_exam_active',
            field=models.BooleanField(default=True, verbose_name='فعال صفحه لیست ازمون ها'),
        ),
        migrations.AddField(
            model_name='site',
            name='list_users_active',
            field=models.BooleanField(default=True, verbose_name='فعال صفحه لیست کاربران'),
        ),
        migrations.AddField(
            model_name='site',
            name='qbank_above_tag',
            field=models.CharField(default='سوالی داری؟ ', max_length=100, verbose_name='تگ بانک سوال'),
        ),
        migrations.AddField(
            model_name='site',
            name='qbank_active',
            field=models.BooleanField(default=True, verbose_name='فعال صفحه بانک سوال'),
        ),
        migrations.AddField(
            model_name='site',
            name='qbank_description',
            field=models.CharField(default='پاسخ به سوالات متداول', max_length=500, verbose_name='توضیحات بانک سوال'),
        ),
        migrations.AddField(
            model_name='site',
            name='qbank_title',
            field=models.CharField(default=' سوالات متداول', max_length=100, verbose_name='عنوان بانک سوال'),
        ),
        migrations.AlterField(
            model_name='site',
            name='short_description',
            field=models.CharField(default='بنیادی که برای تضمین اینده شما به وجود امده است', max_length=255, verbose_name='توضیحات کوتاه'),
        ),
    ]
