# Generated by Django 6.1.1 on 2026-09-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0018_site_list_articles_active_site_list_course_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='users_title_url_name',
            field=models.CharField(default='برترین ها', max_length=100, verbose_name='عنوان لیست کاربران'),
        ),
    ]
