# Generated by Django 6.1.1 on 2026-09-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0019_site_users_title_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='main_page_badge',
            field=models.CharField(default='ظرفیت محدود ترم تابستان ۱۴۰۵', max_length=50, verbose_name='بگ صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_first_button_name',
            field=models.CharField(default='درخواست مشاوره', max_length=50, verbose_name='نام دکمه شماره یک صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_first_button_svg',
            field=models.CharField(default='\n        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">\n            <line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline>\n        </svg>\n    ', max_length=500, verbose_name='svg دکمه شماره یک صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_first_button_url',
            field=models.URLField(default='/free-counseling/', verbose_name='لینک دکمه شماره یک صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_greeting',
            field=models.CharField(default='وجود شما باعث افتخار ماست', max_length=50, verbose_name='گریتینگ صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_second_button_name',
            field=models.CharField(default='بانک سوال', max_length=50, verbose_name='نام دکمه شماره دو صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_second_button_svg',
            field=models.CharField(default='\n        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">\n            <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>\n        </svg>\n    ', max_length=500, verbose_name='svg دکمه شماره دو صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_second_button_url',
            field=models.URLField(default='/qbank/', verbose_name=' لینک دکمه شماره دو صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='site',
            name='qbank_above_tag',
            field=models.CharField(default='سوال نیاز داری', max_length=100, verbose_name='تگ بانک سوال'),
        ),
        migrations.AlterField(
            model_name='site',
            name='qbank_description',
            field=models.CharField(default='بانک سوال رایگان فراسو', max_length=500, verbose_name='توضیحات بانک سوال'),
        ),
        migrations.AlterField(
            model_name='site',
            name='qbank_title',
            field=models.CharField(default='بانک سوال', max_length=100, verbose_name='عنوان بانک سوال'),
        ),
    ]
