# Generated by Django 6.1.1 on 2026-09-26 12:44

import apps.common.file_storage_script_for_model
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0020_site_main_page_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='about_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=80, scale=None, size=None, upload_to=apps.common.file_storage_script_for_model.UploadPath('about-image'), verbose_name='عکس صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_first_stats_name',
            field=models.CharField(default='۸۵٪', max_length=50, verbose_name='نام اول روی تصویر صفحه اصلی '),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_first_stats_number',
            field=models.CharField(default='درصد قبولی', max_length=50, verbose_name='عدد اول روی تصویر صفحه اصلی '),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_first_stats_svg',
            field=models.CharField(default='\n        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">\n            <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>\n        </svg>\n    ', max_length=500, verbose_name='svg اول روی تصویر صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_second_stats_name',
            field=models.CharField(default='تعداد انش اموزان', max_length=50, verbose_name='نام دوم روی تصویر صفحه اصلی '),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_second_stats_number',
            field=models.CharField(default='۸,۵۰۰+', max_length=50, verbose_name='عدد دوم روی تصویر صفحه اصلی '),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_second_stats_svg',
            field=models.CharField(default='\n        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">\n            <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline>\n        </svg>\n    ', max_length=500, verbose_name='svg دوم روی تصویر صفحه اصلی'),
        ),
    ]
