# Generated by Django 6.1.1 on 2026-09-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0021_site_about_img_site_main_page_first_stats_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='first_stats_card_name',
            field=models.CharField(default='دانشجویان', max_length=50, verbose_name='نام نماد امار اول'),
        ),
        migrations.AddField(
            model_name='site',
            name='first_stats_card_number',
            field=models.CharField(default='8500', max_length=50, verbose_name='عدد نماد امار اول'),
        ),
        migrations.AddField(
            model_name='site',
            name='first_stats_card_svg',
            field=models.TextField(default='\n        <svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline>\n        </svg>\n    ', verbose_name='svg نماد امار اول'),
        ),
        migrations.AddField(
            model_name='site',
            name='first_stats_card_symbol',
            field=models.CharField(default='+', max_length=50, verbose_name='علامت نماد امار اول'),
        ),
        migrations.AddField(
            model_name='site',
            name='fourth_stats_card_name',
            field=models.CharField(default='پروژه عملی', max_length=50, verbose_name='نام نماد امار چهار'),
        ),
        migrations.AddField(
            model_name='site',
            name='fourth_stats_card_number',
            field=models.CharField(default='120', max_length=50, verbose_name='عدد نماد امار چهار'),
        ),
        migrations.AddField(
            model_name='site',
            name='fourth_stats_card_svg',
            field=models.TextField(default='\n        <svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="16 18 22 12 16 6"></polyline><polyline points="8 6 2 12 8 18"></polyline>\n        </svg>\n    ', verbose_name='svg نماد امار چهار'),
        ),
        migrations.AddField(
            model_name='site',
            name='fourth_stats_card_symbol',
            field=models.CharField(default='+', max_length=50, verbose_name='علامت نماد امار چهار'),
        ),
        migrations.AddField(
            model_name='site',
            name='second_stats_card_name',
            field=models.CharField(default='شرکت همکار', max_length=50, verbose_name='نام نماد امار دوم'),
        ),
        migrations.AddField(
            model_name='site',
            name='second_stats_card_number',
            field=models.CharField(default='42', max_length=50, verbose_name='عدد نماد امار دوم'),
        ),
        migrations.AddField(
            model_name='site',
            name='second_stats_card_svg',
            field=models.TextField(default='\n        <svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"></rect>\n        </svg>\n    ', verbose_name='svg نماد امار دوم'),
        ),
        migrations.AddField(
            model_name='site',
            name='second_stats_card_symbol',
            field=models.CharField(default='', max_length=50, verbose_name='علامت نماد امار دوم'),
        ),
        migrations.AddField(
            model_name='site',
            name='third_stats_card_name',
            field=models.CharField(default='رضایت', max_length=50, verbose_name='نام نماد امار سوم'),
        ),
        migrations.AddField(
            model_name='site',
            name='third_stats_card_number',
            field=models.CharField(default='98', max_length=50, verbose_name='عدد نماد امار سوم'),
        ),
        migrations.AddField(
            model_name='site',
            name='third_stats_card_svg',
            field=models.TextField(default='\n        <svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="10"></circle><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>\n        </svg>\n    ', verbose_name='svg نماد امار سوم'),
        ),
        migrations.AddField(
            model_name='site',
            name='third_stats_card_symbol',
            field=models.CharField(default='%', max_length=50, verbose_name='علامت نماد امار سوم'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo_svg',
            field=models.TextField(default='\n        <svg width="45" height="45" viewBox="0 0 100 100" fill="none">\n            <defs><linearGradient id="smallGrad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#00f2fe"/><stop offset="100%" stop-color="#4facfe"/></linearGradient></defs>\n            <circle cx="50" cy="50" r="46" stroke="url(#smallGrad)" stroke-width="4" fill="none"/>\n            <circle cx="50" cy="50" r="14" fill="url(#smallGrad)"/>\n        </svg>\n    ', verbose_name='svg لوگو سایت'),
        ),
        migrations.AlterField(
            model_name='site',
            name='main_page_first_button_svg',
            field=models.TextField(default='\n        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">\n            <line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline>\n        </svg>\n    ', verbose_name='svg دکمه شماره یک صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='site',
            name='main_page_first_stats_svg',
            field=models.TextField(default='\n        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">\n            <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>\n        </svg>\n    ', verbose_name='svg اول روی تصویر صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='site',
            name='main_page_second_button_svg',
            field=models.TextField(default='\n        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">\n            <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>\n        </svg>\n    ', verbose_name='svg دکمه شماره دو صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='site',
            name='main_page_second_stats_svg',
            field=models.TextField(default='\n        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">\n            <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline>\n        </svg>\n    ', verbose_name='svg دوم روی تصویر صفحه اصلی'),
        ),
    ]
