# Generated by Django 6.1.1 on 2026-09-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0022_site_first_stats_card_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='main_page_blog_active',
            field=models.BooleanField(default=True, verbose_name='فعال کردن قسمت مقالات در صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_blog_name',
            field=models.CharField(default='مقالات آموزشی', max_length=100, verbose_name='نام قسمت مقالات در صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_course_name',
            field=models.CharField(default='بهترین دوره ها', max_length=100, verbose_name='نام قسمت دوره ها در صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_course_section_active',
            field=models.BooleanField(default=True, verbose_name='فعال کردن قسمت دوره ها در صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_mentors_active',
            field=models.BooleanField(default=True, verbose_name='فعال کردن قسمت افراد در صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='site',
            name='main_page_mentors_name',
            field=models.CharField(default='برترین ها', max_length=100, verbose_name='نام قسمت افراد در صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='site',
            name='first_stats_card_name',
            field=models.CharField(default='دانش اموزان', max_length=50, verbose_name='نام نماد امار اول'),
        ),
        migrations.AlterField(
            model_name='site',
            name='second_stats_card_name',
            field=models.CharField(default='مدرسه', max_length=50, verbose_name='نام نماد امار دوم'),
        ),
    ]
