"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import STATICFILES_DIRS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%2na27rob(n157r#mf3@d#354%3x@cg5sla9)9^hool(6e88h^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
THIRD_PARTY_APPS = [
    "phonenumber_field",
    "django_ckeditor_5",
    "django_jalali",


]
DEV_APPS = [
   "debug_toolbar",

]
MAIN_APPS = [
    "apps.categories",
    "apps.users.accounts",
    "apps.users.advisers",
    "apps.users.managers",
    "apps.users.students",
    "apps.users.teachers",
    "apps.classes",
    "apps.content",
    "apps.communication",
    "apps.exams",
    "apps.live_classes",
    "apps.payments",
    "apps.progress",
    "apps.questions",
    "apps.reports",
    "apps.schools",
    "apps.subscriptions",
    "apps.article",
    "apps.common",
    "apps.sitesetting",

]
if DEBUG:
    INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + DEV_APPS  + MAIN_APPS

else:
    INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + MAIN_APPS


DJANGO_MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
THIRD_PARTY_MIDDLEWARE=[]
DEV_MIDDLEWARE=[
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

MAIN_MIDDLEWARE=[
    "apps.sitesetting.middleware.SiteMiddleware",
]

if DEBUG:
    MIDDLEWARE = DJANGO_MIDDLEWARE + THIRD_PARTY_MIDDLEWARE + DEV_MIDDLEWARE + MAIN_MIDDLEWARE

else:
    MIDDLEWARE = DJANGO_MIDDLEWARE + THIRD_PARTY_MIDDLEWARE + MAIN_MIDDLEWARE


HTML_MINIFY = True
HTML_MINIFY_EXCLUDE_EXTENSIONS = (
    'json',
    'xml',
)

# image compress
DJANGORESIZED_DEFAULT_SIZE = None
DJANGORESIZED_DEFAULT_QUALITY = 80
DJANGORESIZED_DEFAULT_FORCE_FORMAT = "WEBP"
DJANGORESIZED_DEFAULT_KEEP_META = False
DJANGORESIZED_DEFAULT_NORMALIZE_ROTATION = True
DJANGORESIZED_DEFAULT_FORMAT_EXTENSIONS = {
    "WEBP": ".webp",
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "apps.sitesetting.context_processors.get_site",

            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT =  BASE_DIR / 'static'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# django debug
INTERNAL_IPS = [

    "127.0.0.1",
    "localhost",

]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OTP_EXPIRATIONS_SECONDS = 60 * 3
OTP_EXPIRATIONS_RANGE_START = 1000
OTP_EXPIRATIONS_RANGE_END = 1000
DEFAULT_PASSWORD = "0000"
LOGIN_TEMP = 3
AUTH_USER_MODEL = 'accounts.User'
# LOGIN_URL = "user:login"
# LOGIN_REDIRECT_URL = "/"
JALALI_SETTINGS = {

    "ADMIN_JS_STATIC_FILES": [
        "admin/jquery.ui.datepicker.jalali/scripts/jquery-1.10.2.min.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js",
        "admin/jquery.ui.datepicker.jalali/scripts/calendar.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js",
        "admin/main.js",
    ],

    "ADMIN_CSS_STATIC_FILES": {
        "all": [
            "admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css",
            "admin/css/main.css",
        ]
    },
}

JALALI_DISPLAY = {
    "DATE_FORMAT": "%Y/%m/%d",
    "DATETIME_FORMAT": "%H:%M - %Y/%m/%d ",
    "AUTO_CONVERT": True,
}

# phone number config
PHONENUMBER_DEFAULT_FORMAT = "NATIONAL"
PHONENUMBER_DEFAULT_REGION = "IR"

# cke config

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": {
            "items": ["undo","redo","|","selectAll","findAndReplace","|","heading","|",
                      "fontFamily","fontSize","fontColor","fontBackgroundColor","|",
                      "bold","italic","underline","strikethrough","subscript","superscript",
                      "code","highlight","|","alignment","|","link","imageUpload",
                      "mediaEmbed","|","bulletedList","numberedList","todoList","outdent",
                      "indent","|","blockQuote","codeBlock","horizontalLine","|","insertTable","|",
                      "specialCharacters","|","removeFormat",
            ],
            "shouldNotGroupWhenFull": True,
        },
        "language": "fa",
        "heading": {
            "options": [
                {"model": "paragraph","title": "پاراگراف","class": "ck-heading_paragraph",},
                {"model": "heading1","view": "h1","title": "عنوان ۱","class": "ck-heading_heading1",},
                {"model": "heading2","view": "h2","title": "عنوان ۲","class": "ck-heading_heading2",},
                {"model": "heading3","view": "h3","title": "عنوان ۳","class": "ck-heading_heading3",},
                {"model": "heading4","view": "h4","title": "عنوان ۴","class": "ck-heading_heading4",},
            ],
        },
        "fontFamily": {
            "options": [
                "default",
                "Vazirmatn",
                "Tahoma",
                "Arial",
                "Times New Roman",
            ],
            "supportAllValues": True,
        },
        "fontSize": {
            "options": [10,11,12,13,14,15,16,17,18,19,20,22,24,28,32,36,48,
            ],
        },
        "fontColor": {
            "colors": [
                {"color": "#000000","label": "مشکی",},
                {"color": "#FF0000","label": "قرمز",},
                {"color": "#0000FF","label": "آبی",},
                {"color": "#008000","label": "سبز",},
                {"color": "#FFA500","label": "نارنجی",},
                {"color": "#800080","label": "بنفش",},
                {"color": "#808080","label": "خاکستری",},
            ],
        },
        "fontBackgroundColor": {
            "colors": [
                {"color": "#FFFF00","label": "زرد",},
                {"color": "#00FF00","label": "سبز",},
                {"color": "#00FFFF","label": "فیروزه‌ای",},
                {"color": "#FFB6C1","label": "صورتی",},
            ],
        },
        "alignment": {
            "options": ["left","center","right","justify",
            ],
        },
        "image": {
            "toolbar": ["imageTextAlternative","|","imageStyle:inline","imageStyle:block","imageStyle:side","|","linkImage",
            ],
        },
        "table": {
            "contentToolbar": ["tableColumn","tableRow","mergeTableCells","tableProperties","tableCellProperties",
            ],
        },
        "link": {"addTargetToExternalLinks": True,"defaultProtocol": "https://",
        },
    },
}

CKEDITOR_5_FILE_UPLOAD_PERMISSION = "user"
# CKEDITOR_5_FILE_STORAGE = 'config.storage.CKEditorMediaStorage'
