"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%2na27rob(n157r#mf3@d#354%3x@cg5sla9)9^hool(6e88h^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
THIRD_PARTY_APPS = [
    "phonenumber_field",
    "django_ckeditor_5",
]
MAIN_APPS = [
    "apps.categories",
    "apps.users.accounts",
    "apps.users.advisers",
    "apps.users.managers",
    "apps.users.students",
    "apps.users.teachers",
    "apps.classes",
    "apps.content",
    "apps.communication",
    "apps.exams",
    "apps.live_classes",
    "apps.payments",
    "apps.progress",
    "apps.questions",
    "apps.reports",
    "apps.schools",
    "apps.subscriptions",
    "apps.article",
    "apps.common",
    "apps.sitesetting",

]
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + MAIN_APPS


DJANGO_MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
THIRD_PARTY_MIDDLEWARE=[]
MAIN_MIDDLEWARE=[
    "apps.sitesetting.middleware.SiteMiddleware"
]

MIDDLEWARE = DJANGO_MIDDLEWARE + THIRD_PARTY_MIDDLEWARE + MAIN_MIDDLEWARE

# html minify
HTML_MINIFY = True
HTML_MINIFY_EXCLUDE_EXTENSIONS = (
    'json',
    'xml',
)

# THUMBNAIL
THUMBNAIL_DEFAULT_OPTIONS = {
    'format': 'WEBP',      # همیشه WebP تولید کنه
    'quality': 70,         # کیفیت پیش‌فرض (می‌تونی تغییر بدی)
    'crop': 'center',      # همیشه از مرکز crop کنه (اگر crop فعال باشه)
    'optimize': True,      # بهینه‌سازی lossless با Pillow
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "apps.sitesettings.context_processors.get_site",

            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OTP_EXPIRATIONS_SECONDS = 60 * 3
OTP_EXPIRATIONS_RANGE_START = 1000
OTP_EXPIRATIONS_RANGE_END = 1000
DEFAULT_PASSWORD = "0000"
LOGIN_TEMP = 3
AUTH_USER_MODEL = 'accounts.User'
# LOGIN_URL = "user:login"
# LOGIN_REDIRECT_URL = "/"
JALALI_DATE_DEFAULTS = {
    # if change it to true then all dates of the list_display will convert to the Jalali.
    "LIST_DISPLAY_AUTO_CONVERT": True,
    "Strftime": {
        "date": "%Y/%m/%d",
        "datetime": "%H:%M - %Y/%m/%d ",
    },
    "Static": {
        "js": [
            "admin/js/django_jalali.min.js",
        ],
        "css": {
            "all": [
                "admin/css/django_jalali.min.css",
            ]
        },
    },
}

# phone number config
PHONENUMBER_DEFAULT_FORMAT = "NATIONAL"
PHONENUMBER_DEFAULT_REGION = "IR"

# cke config

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": {
            "items": [
                # History
                "undo",
                "redo",

                "|",

                # Selection / search
                "selectAll",
                "findAndReplace",

                "|",

                # Headings
                "heading",

                "|",

                # Font
                "fontFamily",
                "fontSize",
                "fontColor",
                "fontBackgroundColor",

                "|",

                # Text formatting
                "bold",
                "italic",
                "underline",
                "strikethrough",
                "subscript",
                "superscript",
                "code",
                "highlight",

                "|",

                # Paragraph
                "alignment",

                "|",

                # Links / media
                "link",
                "imageUpload",
                "mediaEmbed",

                "|",

                # Lists
                "bulletedList",
                "numberedList",
                "todoList",
                "outdent",
                "indent",

                "|",

                # Blocks
                "blockQuote",
                "codeBlock",
                "horizontalLine",

                "|",

                # Tables
                "insertTable",

                "|",

                # Characters
                "specialCharacters",

                "|",

                # Clean
                "removeFormat",
            ],

            "shouldNotGroupWhenFull": True,
        },

        "language": "fa",

        # -------------------------
        # Heading
        # -------------------------
        "heading": {
            "options": [
                {
                    "model": "paragraph",
                    "title": "پاراگراف",
                    "class": "ck-heading_paragraph",
                },
                {
                    "model": "heading1",
                    "view": "h1",
                    "title": "عنوان ۱",
                    "class": "ck-heading_heading1",
                },
                {
                    "model": "heading2",
                    "view": "h2",
                    "title": "عنوان ۲",
                    "class": "ck-heading_heading2",
                },
                {
                    "model": "heading3",
                    "view": "h3",
                    "title": "عنوان ۳",
                    "class": "ck-heading_heading3",
                },
                {
                    "model": "heading4",
                    "view": "h4",
                    "title": "عنوان ۴",
                    "class": "ck-heading_heading4",
                },
            ],
        },

        # -------------------------
        # Font Family
        # -------------------------
        "fontFamily": {
            "options": [
                "default",
                "Vazirmatn",
                "Tahoma",
                "Arial",
                "Times New Roman",
            ],
            "supportAllValues": True,
        },

        # -------------------------
        # Font Size
        # -------------------------
        "fontSize": {
            "options": [
                10,
                12,
                14,
                16,
                18,
                20,
                22,
                24,
                28,
                32,
                36,
                48,
            ],
        },

        # -------------------------
        # Font Color
        # -------------------------
        "fontColor": {
            "colors": [
                {
                    "color": "#000000",
                    "label": "مشکی",
                },
                {
                    "color": "#FF0000",
                    "label": "قرمز",
                },
                {
                    "color": "#0000FF",
                    "label": "آبی",
                },
                {
                    "color": "#008000",
                    "label": "سبز",
                },
                {
                    "color": "#FFA500",
                    "label": "نارنجی",
                },
                {
                    "color": "#800080",
                    "label": "بنفش",
                },
                {
                    "color": "#808080",
                    "label": "خاکستری",
                },
            ],
        },

        # -------------------------
        # Background Color
        # -------------------------
        "fontBackgroundColor": {
            "colors": [
                {
                    "color": "#FFFF00",
                    "label": "زرد",
                },
                {
                    "color": "#00FF00",
                    "label": "سبز",
                },
                {
                    "color": "#00FFFF",
                    "label": "فیروزه‌ای",
                },
                {
                    "color": "#FFB6C1",
                    "label": "صورتی",
                },
            ],
        },

        # -------------------------
        # Alignment
        # -------------------------
        "alignment": {
            "options": [
                "left",
                "center",
                "right",
                "justify",
            ],
        },

        # -------------------------
        # Image
        # -------------------------
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:inline",
                "imageStyle:block",
                "imageStyle:side",
                "|",
                "linkImage",
            ],
        },

        # -------------------------
        # Table
        # -------------------------
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties",
            ],
        },

        # -------------------------
        # Link
        # -------------------------
        "link": {
            "addTargetToExternalLinks": True,
            "defaultProtocol": "https://",
        },
    },
}

CKEDITOR_5_FILE_UPLOAD_PERMISSION = "user"
# CKEDITOR_5_FILE_STORAGE = 'config.storage.CKEditorMediaStorage'
