# Generated by Django 6.1.1 on 2026-09-21 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_lessoncategories'),
        ('schools', '0001_initial'),
        ('students', '0002_alter_student_city_alter_student_grade_and_more'),
        ('teachers', '0002_remove_teacher_grade_alter_teacher_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='categories.gradecategories', verbose_name='پایه')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='categories.lessoncategories', verbose_name='درس')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='categories.majorcategories', verbose_name='رشته')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school', verbose_name='مدرسه')),
                ('student', models.ManyToManyField(related_name='classes', to='students.student', verbose_name='دانش اموزان')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='teachers.teacher', verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس ها',
                'ordering': ['-pk'],
            },
        ),
    ]
