# Generated by Django 6.1.1 on 2026-09-21 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='sort_number',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب'),
        ),
        migrations.AddField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
    ]
