# Generated by Django 6.1.1 on 2026-09-24 17:39

import apps.common.file_storage_script_for_model
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_created_at_alter_class_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=False, quality=80, scale=None, size=None, upload_to=apps.common.file_storage_script_for_model.UploadPath('classes/'), verbose_name='عکس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='رایگان'),
        ),
        migrations.AddField(
            model_name='class',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='عمومی'),
        ),
        migrations.AlterField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
