# Generated by Django 6.1.1 on 2026-09-24 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_blogcategories_created_at_and_more'),
        ('classes', '0005_class_image_class_is_free_class_is_public_and_more'),
        ('schools', '0004_alter_school_created_at_alter_school_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='categories.gradecategories', verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='categories.lessoncategories', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='class',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='categories.majorcategories', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school', verbose_name='مدرسه'),
        ),
    ]
