# Generated by Django 6.1.1 on 2026-09-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_class_grade_alter_class_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='first_tag',
            field=models.CharField(blank=True, default='پشتیبانی ۲۴/۷', max_length=50, null=True, verbose_name='تگ اول'),
        ),
        migrations.AddField(
            model_name='class',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='class',
            name='second_tag',
            field=models.CharField(blank=True, default='گواهی معتبر', max_length=50, null=True, verbose_name='تگ دوم'),
        ),
        migrations.AddField(
            model_name='class',
            name='summery',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='class',
            name='third_tag',
            field=models.CharField(blank=True, default='پروژه محور', max_length=50, null=True, verbose_name='تگ سوم'),
        ),
    ]
