# Generated by Django 6.1.1 on 2026-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_class_first_tag_class_price_class_second_tag_and_more'),
        ('students', '0003_alter_student_managers_student_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes', to='students.student', verbose_name='دانش اموزان'),
        ),
    ]
