# Generated by Django 6.1.1 on 2026-09-24 19:42

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_class_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
