# Generated by Django 6.1.1 on 2026-09-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_class_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-sort_number', '-pk'], 'verbose_name': 'کلاس', 'verbose_name_plural': 'کلاس ها'},
        ),
    ]
