# Generated by Django 6.1.1 on 2026-09-21 21:40

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_citycategories_created_at_citycategories_updated_at_and_more'),
        ('schools', '0002_school_created_at_school_sort_number_and_more'),
        ('students', '0002_alter_student_city_alter_student_grade_and_more'),
        ('teachers', '0002_remove_teacher_grade_alter_teacher_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان')),
                ('section', models.CharField(blank=True, max_length=255, null=True, verbose_name='مبحث')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name=' نام استان محل برگذاری')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شهر محل برگذاری')),
                ('type_of_quiz', models.CharField(blank=True, max_length=255, null=True, verbose_name='محل و نحوه برگذاری')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='هزینه')),
                ('time_minutes', models.PositiveIntegerField(default=0, verbose_name='(دقیقه) تایمر')),
                ('start_at', models.DateTimeField(verbose_name='زمان برگذاری')),
                ('stop_at', models.DateTimeField(verbose_name='زمان پایان')),
                ('last_enter', models.DateTimeField(verbose_name='اخرین زمان ورود')),
                ('corrected_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصحیح')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='حداکثر نمره')),
                ('score', models.FloatField(default=1, verbose_name='ضریب')),
                ('capacity', models.PositiveSmallIntegerField(default=1, verbose_name='ظرفیت')),
                ('filled_capacity', models.PositiveSmallIntegerField(default=0, verbose_name=' ظرفیت پر شده')),
                ('is_online', models.BooleanField(default=True, verbose_name='انلاین')),
                ('change_the_order', models.BooleanField(default=True, verbose_name=' عوض کردن ترتیب سوالات')),
                ('have_negative_score', models.BooleanField(default=True, verbose_name='دارای نمره منفی')),
                ('start_set_report', models.BooleanField(default=False, verbose_name='شروع به تصحیح')),
                ('allow_to_edit_the_answered_questions', models.BooleanField(default=True, verbose_name='امکان ویرایش سوالات پاسخ داده شده')),
                ('allow_return_to_questions', models.BooleanField(default=True, verbose_name='برگشتن به عقب')),
                ('allow_to_edit_the_question_after_the_user_finish', models.BooleanField(default=True, verbose_name='اجازه به ویرایش پاسخ بعد از اتمام کاربر و قبل از اتمام وقت')),
                ('status', models.CharField(blank=True, choices=[('همه وضعیت ها ', 'همه وضعیت ها '), ('در انتظار شروع', 'در انتظار شروع'), ('شروع شده', 'شروع شده'), ('پایان یافته', 'پایان یافته'), ('در انتظار تصحیح', 'در انتظار تصحیح'), ('اعلام نتایج', 'اعلام نتایج'), ('غیرفعال', 'غیرفعال'), ('کنسل شده', 'کنسل شده')], default='در انتظار شروع', max_length=55, null=True, verbose_name='وضعیت')),
                ('reduce_percent_of_negative_score', models.SmallIntegerField(default=30, verbose_name='درصد کم کردن از نمره در ازای هر سوال اشتباه')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات')),
                ('entered_student', models.ManyToManyField(blank=True, editable=False, related_name='exam_entered_student', to='students.student', verbose_name='دانش اموز شرکت کرده')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='categories.gradecategories', verbose_name='پایه')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='categories.lessoncategories', verbose_name='درس')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='categories.majorcategories', verbose_name='رشته')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='schools.school', verbose_name='مدرسه')),
                ('selected_student', models.ManyToManyField(blank=True, related_name='exam', to='students.student', verbose_name='دانش اموز انتخاب شده')),
                ('teacher', models.ManyToManyField(related_name='exam', to='teachers.teacher', verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'ازمون جامع',
                'verbose_name_plural': 'ازمون های جامع',
                'ordering': ['-sort_number', '-pk'],
            },
        ),
    ]
