# Generated by Django 6.1.1 on 2026-09-24 21:54

import apps.common.file_storage_script_for_model
import apps.common.models_fields
import django.db.models.deletion
import django_ckeditor_5.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_blogcategories_created_at_and_more'),
        ('exams', '0003_alter_exam_created_at_alter_exam_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=False, quality=80, scale=None, size=None, upload_to=apps.common.file_storage_script_for_model.UploadPath('classes/'), verbose_name='عکس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='رایگان'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='عمومی'),
        ),
        migrations.AddField(
            model_name='exam',
            name='summery',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='categories.citycategories', verbose_name='نام شهر محل برگذاری'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='corrected_at',
            field=apps.common.models_fields.BaseJalaliDateTimeField(blank=True, null=True, verbose_name='زمان تصحیح'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='last_enter',
            field=apps.common.models_fields.BaseJalaliDateTimeField(verbose_name='اخرین زمان ورود'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='categories.provincecategories', verbose_name=' نام استان محل برگذاری'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_at',
            field=apps.common.models_fields.BaseJalaliDateTimeField(verbose_name='زمان برگذاری'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='stop_at',
            field=apps.common.models_fields.BaseJalaliDateTimeField(verbose_name='زمان پایان'),
        ),
    ]
