# Generated by Django 6.1.1 on 2026-09-25 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_blogcategories_created_at_and_more'),
        ('exams', '0004_exam_image_exam_is_free_exam_is_public_exam_summery_and_more'),
        ('schools', '0004_alter_school_created_at_alter_school_updated_at'),
        ('teachers', '0003_alter_teacher_managers_teacher_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-sort_number', '-pk'], 'verbose_name': 'ازمون ', 'verbose_name_plural': 'ازمون ها'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='categories.gradecategories', verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='categories.lessoncategories', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='categories.majorcategories', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='schools.school', verbose_name='مدرسه'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='exam', to='teachers.teacher', verbose_name='معلم'),
        ),
    ]
