# Generated by Django 6.1.1 on 2026-09-21 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_lessoncategories'),
        ('managers', '0002_alter_manager_city_alter_manager_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='categories.citycategories', verbose_name='شهر')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='managers.manager', verbose_name='مدرسه')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='categories.provincecategories', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'مدرسه',
                'verbose_name_plural': 'مدارس',
                'ordering': ['-pk'],
            },
        ),
    ]
