# Generated by Django 6.1.1 on 2026-09-23 19:50

import apps.common.file_storage_script_for_model
import django.db.models.deletion
import django_ckeditor_5.fields
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_blogcategories_alter_citycategories_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('reading_time', models.IntegerField(default=10, verbose_name='زمان مطالعه (دقیقه)')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان')),
                ('summery', models.CharField(max_length=500, verbose_name='خلاصه')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=False, quality=80, scale=None, size=None, upload_to=apps.common.file_storage_script_for_model.UploadPath('articles-images'), verbose_name='عکس')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.common.file_storage_script_for_model.UploadPath('article-files'), verbose_name='فایل')),
                ('name_for_file', models.CharField(max_length=255, verbose_name='عنوان')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='categories.blogcategories', verbose_name='دسته بندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-sort_number', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('sort_number', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='article.article', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-sort_number', '-pk'],
            },
        ),
    ]
