# Generated by Django 6.1.1 on 2026-09-23 21:14

import django.db.models.manager
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletags',
            options={'ordering': ['-sort_number', '-pk'], 'verbose_name': 'تگ مقاله', 'verbose_name_plural': 'تگ های مقاله'},
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='articletags',
            managers=[
                ('jalali_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name_for_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فایل'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='articletags',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='articletags',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
    ]
