# Generated by Django 6.1.1 on 2026-09-24 13:34

import apps.common.models_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articletags_options_alter_article_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletags',
            name='url',
            field=models.URLField(default='#', verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=apps.common.models_fields.BaseJalaliDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=apps.common.models_fields.BaseJalaliDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='articletags',
            name='created_at',
            field=apps.common.models_fields.BaseJalaliDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='articletags',
            name='updated_at',
            field=apps.common.models_fields.BaseJalaliDateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی'),
        ),
    ]
