# Generated by Django 6.1.1 on 2026-09-21 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisers', '0001_initial'),
        ('categories', '0002_lessoncategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adviser', to='categories.citycategories', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adviser', to='categories.provincecategories', verbose_name='استان'),
        ),
    ]
